### ISSUE TITLE
Training Scripts

### ISSUE THREAD

**Issue by maxtrem** [Kungbib/swedish-spacy#1]
Hej! 

I am trying to train a custom model Swedish. Would it be possible to share the training scripts/code that you used for training the model? That would be really helpful.

Thanks!

**Comment by Nuccy90** [comment]
Hi, I used the built-in `spacy train` command from the command line, You can find more information [here](https://spacy.io/api/cli#train). Unless you are asking about the scripts to convert SUC 3.0 into a format compatible with spaCy?
