### ISSUE TITLE
No such file or directory: sv_model_upos/sv_model0/sv_model_upos0-0.0.0/vocab/lexemes.bin

### ISSUE THREAD

**Issue by hasnainroopawalla** [Kungbib/swedish-spacy#2]
I downloaded the zip files, unzipped them. 
But when I run spacy.load(), I get the error `No such file or directory: sv_model_upos/sv_model0/sv_model_upos0-0.0.0/vocab/lexemes.bin`

I have correctly specified the path of the inner folder as well (model path) but there is no such file as `lexemes.bin`
How do I fix this?

**Comment by Nuccy90** [comment]
Hi, I think this might be due to an older version of spaCy. Please check whether you have spaCy 2.3.2 and let me know if the problem persists.
