### ISSUE TITLE
spaCy 3.0

### ISSUE THREAD

**Issue by Lundez** [Kungbib/swedish-spacy#4]
Does the model already support 3.0 or do you need to add something new?
Would it be possible to add a transformer pipeline on top of 3.0 support?👍

**Comment by Nuccy90** [comment]
Hi! I am working right now at two new transformer models in spaCy 3.0. Stay tuned!

**Comment by Lundez** [comment]
@Nuccy90 🥳  Amazing!

Is there any progress in integrating this into spaCy itself? Can I be of help somehow?

**Comment by Nuccy90** [comment]
I guess they have been quite busy with the 3.0 release but we will make a new attempt at pitching Swedish as a core model. Maybe you could go to the discussion on their GitHub and suggest it as a feature, we can make a stronger case if they see there is a need in the community :)

**Comment by Lundez** [comment]
@Nuccy90 I take it as `sv_pipeline-0.0.0.tar.gz` & `sv_tagger-0.0.0.tar.gz` are the transformer based models based of the updated README?
Found at https://data.kb.se/datasets/2020/10/swedish_nlp/spacy/

The three other models (UPOS, UPOS_BUP & XPOS) are all the "normal" spacy model?

**Comment by Nuccy90** [comment]
Yes, thank you for clarifying that!

**Comment by Lundez** [comment]
I'll close this issue, thanks for managing this!

Now onto getting`spacy` to integrate pipeline by default 😄
