### ISSUE TITLE
"Old models" dont work on spacy 3.0+

### ISSUE THREAD

**Issue by Lundez** [Kungbib/swedish-spacy#5]
It seems Spacy updated their format, is it possible to update the old models?
Getting a `config.cfg` couldn't be found error while trying to load with spacy 3.0+

**Comment by Nuccy90** [comment]
If you would like to use spaCy 3.0 you should use the new models, because the new version is not backwards compatible with the old 2.3.2 models.

**Comment by Lundez** [comment]
Ok, too bad. I'd be happy to have less accuracy in exchange for better performance on low-end gear. Swapping between the models will be annoying in this setup.

But I 100% understand that there's neither time, energy or money to fix.
Thanks

**Comment by Nuccy90** [comment]
Are you sure you need to upgrade to spaCy 3.0? If you need the old models you can still have an environment with spaCy 2.3.2 as long as you like, they haven't discontinued support or anything :slightly_smiling_face:

**Comment by Lundez** [comment]
@Nuccy90 I wanna use both models when on my computer. 
But yeah, I'll have to use  `virtualenv` to solve this :)
