### ISSUE TITLE
ERROR: pip's dependency

### ISSUE THREAD

**Issue by gustavengstrom** [Kungbib/swedish-spacy#7]
Hi,

pip install sv_pipeline-0.0.0.tar.gz

Results in:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spacy-transformers 1.0.6 requires spacy<4.0.0,>=3.1.0, but you have spacy 3.0.7 which is incompatible.

Are there really breaking changes in spacy 3.1?

**Comment by Nuccy90** [comment]
Hi,

The problems seems to stem from spacy-transformers, I looked up their requirements and it does require spacy>=3.1, so I suggest you just downgrade to the previous version of spacy-transformers and all should work just as fine.

Regarding the pipeline, [here](https://spacy.io/usage/v3-1#upgrading) they talk about compatibility issues between v. 3.0 and 3.1, it seems to be the case that even if you see a warning, everything should still work normally.

So you can either downgrade spacy-transformers or upgrade spaCy and it should work either way.
