### ISSUE TITLE
Spacy 3.2 ??

### ISSUE THREAD

**Issue by osterhult** [Kungbib/swedish-spacy#9]
Hi there,

Is it possible to update sv_pipeline-0.0.0.tar.gz so it can handle latest Stacy version (3.2) ??
Or can I do it myself?

Best regards,
/Magnus

**Comment by Nuccy90** [comment]
Hi,

Unfortunately we can't retrain the model evey time they release a new version, but we do have the goal to get Swedish included in the core models at some point, so the model will be automatically updated with every release.

They still say that pipelines trained in spaCy 3.0 and 3.1 should be compatible, so you can just change the requirements as indicated [here](https://spacy.io/usage/v3-2#upgrading) and check that everything works as expected.

**Comment by osterhult** [comment]
Hej again,

Thanks for the replay. I got my code going with older versions of the libraries. But I surely will try to upgrade them and also crossing my fingers that you get the Swedish model included in the core. Great job over all by the way. :)
